#
# ~/.bashrc
#

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

# If running from tty1 start sway
#if [ "$(tty)" = "/dev/tty1" ]; then
	#exec sway
#fi

alias ls='ls --color=auto'
PS1=' -> '

# Load environment variables
source $HOME/.config/profile/env.conf
